name: Java CI
on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Test with Maven
        run: mvn -B test --file pom.xml

      - name: Publish test results
        uses: scacap/action-surefire-report@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Test Results
          fail_if_no_tests: true

      - name: Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

  security-check:
    name: Security Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17 for Security Scan
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Dependency Check
        uses: jeremylong/DependencyCheck@v6
        with:
          format: 'ALL'
        continue-on-error: true

      - name: Publish Dependency Check results
        uses: actions/upload-artifact@v3
        with:
          name: Dependency-Check-Report
          path: |
            **/dependency-check-report.*
